# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required. version: 2 must be used with build.os. To specify Python version, have to use build.tools.python
version: 2
build:
  os: "ubuntu-20.04" # RTD v2 only supports ubuntu-22.04 and ubuntu-20.04. But ubuntu-22.04 does not support building API documentation. Use ubuntu-20.04 instead
  tools: 
    python: "3.6" # python 3.5 is used in CI, but RTD v2 does not support python 3.5 any more. Python 3.6 is used instead

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip
  - pdf

# Optionally set the requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

submodules:
  include: all
